-- Migration: 20260814000000_register_all_wards.sql
-- Purpose: Register the missing ward reference records so the app lists all
-- 111 wards matching the BRANCH NOMI sheet. This is REFERENCE DATA ONLY:
-- no nominations/votes are created, and no existing rows are modified.
-- Ward-level results will continue to be entered via the in-app matrix editor.
--
-- This is idempotent: ON CONFLICT (ward_number) DO NOTHING makes it safe to
-- re-run on any environment (local or hosted).

INSERT INTO wards (ward_number, zone_id)
SELECT w.ward_number, z.id
FROM (VALUES
  -- AMON NGULELE
  (12), (13), (16), (18), (23), (91), (92),
  -- ANDREW MAPHETO
  (7),
  -- BAVUMILE VILAKAZI
  (20), (21), (22), (32), (35), (36), (37), (38), (39), (42), (93), (94), (106),
  -- DAVID BOPAPE
  (82), (83), (84), (85), (88), (98), (112),
  -- DIZA PHUTHINI
  (25), (27), (28), (30), (31),
  -- GRACE FLATELA
  (41), (43), (46),
  -- OSKA MABIKA
  (68), (69), (70), (71),
  -- PAUL SEHLOHO
  (40), (50), (51), (52), (53), (54), (55), (56), (57),
  -- SELOPE THEMA
  (97), (105),
  -- ZONE 10
  (61), (62), (63), (108)
) AS w(ward_number)
LEFT JOIN zones z ON z.name = (
  CASE w.ward_number
    WHEN 12 THEN 'AMON NGULELE'
    WHEN 13 THEN 'AMON NGULELE'
    WHEN 16 THEN 'AMON NGULELE'
    WHEN 18 THEN 'AMON NGULELE'
    WHEN 23 THEN 'AMON NGULELE'
    WHEN 91 THEN 'AMON NGULELE'
    WHEN 92 THEN 'AMON NGULELE'
    WHEN 7 THEN 'ANDREW MAPHETO'
    WHEN 20 THEN 'BAVUMILE VILAKAZI'
    WHEN 21 THEN 'BAVUMILE VILAKAZI'
    WHEN 22 THEN 'BAVUMILE VILAKAZI'
    WHEN 32 THEN 'BAVUMILE VILAKAZI'
    WHEN 35 THEN 'BAVUMILE VILAKAZI'
    WHEN 36 THEN 'BAVUMILE VILAKAZI'
    WHEN 37 THEN 'BAVUMILE VILAKAZI'
    WHEN 38 THEN 'BAVUMILE VILAKAZI'
    WHEN 39 THEN 'BAVUMILE VILAKAZI'
    WHEN 42 THEN 'BAVUMILE VILAKAZI'
    WHEN 93 THEN 'BAVUMILE VILAKAZI'
    WHEN 94 THEN 'BAVUMILE VILAKAZI'
    WHEN 106 THEN 'BAVUMILE VILAKAZI'
    WHEN 82 THEN 'DAVID BOPAPE'
    WHEN 83 THEN 'DAVID BOPAPE'
    WHEN 84 THEN 'DAVID BOPAPE'
    WHEN 85 THEN 'DAVID BOPAPE'
    WHEN 88 THEN 'DAVID BOPAPE'
    WHEN 98 THEN 'DAVID BOPAPE'
    WHEN 112 THEN 'DAVID BOPAPE'
    WHEN 25 THEN 'DIZA PHUTHINI'
    WHEN 27 THEN 'DIZA PHUTHINI'
    WHEN 28 THEN 'DIZA PHUTHINI'
    WHEN 30 THEN 'DIZA PHUTHINI'
    WHEN 31 THEN 'DIZA PHUTHINI'
    WHEN 41 THEN 'GRACE FLATELA'
    WHEN 43 THEN 'GRACE FLATELA'
    WHEN 46 THEN 'GRACE FLATELA'
    WHEN 68 THEN 'OSKA MABIKA'
    WHEN 69 THEN 'OSKA MABIKA'
    WHEN 70 THEN 'OSKA MABIKA'
    WHEN 71 THEN 'OSKA MABIKA'
    WHEN 40 THEN 'PAUL SEHLOHO'
    WHEN 50 THEN 'PAUL SEHLOHO'
    WHEN 51 THEN 'PAUL SEHLOHO'
    WHEN 52 THEN 'PAUL SEHLOHO'
    WHEN 53 THEN 'PAUL SEHLOHO'
    WHEN 54 THEN 'PAUL SEHLOHO'
    WHEN 55 THEN 'PAUL SEHLOHO'
    WHEN 56 THEN 'PAUL SEHLOHO'
    WHEN 57 THEN 'PAUL SEHLOHO'
    WHEN 97 THEN 'SELOPE THEMA'
    WHEN 105 THEN 'SELOPE THEMA'
    WHEN 61 THEN 'ZONE 10'
    WHEN 62 THEN 'ZONE 10'
    WHEN 63 THEN 'ZONE 10'
    WHEN 108 THEN 'ZONE 10'
    ELSE NULL
  END
)
WHERE z.id IS NOT NULL
ON CONFLICT (ward_number) DO NOTHING;